djstripe/urls.py
# -*- coding: utf-8 -*-
"""
.. module:: djstripe.urls.

  :synopsis: dj-stripe - Urls related to the djstripe app.

  Wire this into the root URLConf this way::

      url(r'^stripe/', include('djstripe.urls', namespace="djstripe")),
      # url can be changed
      # Call to 'djstripe.urls' and 'namespace' must stay as is

  Call it from reverse()::

      reverse("djstripe:subscribe")

  Call from url tag::

      {% url 'djstripe:subscribe' %}

.. moduleauthor:: @pydanny
"""
from __future__ import absolute_import, division, print_function, unicode_literals

from django.conf.urls import url

from . import settings as app_settings
from . import views


app_name = "djstripe"

urlpatterns = [
    # HTML views
    url(
        r"^subscribe/$",
        views.SubscribeView.as_view(),
        name="subscribe"
    ),
    url(
        r"^cancel/subscription/$",
        views.CancelSubscriptionView.as_view(),
        name="cancel_subscription"
    ),

    # Webhook
    url(
        app_settings.DJSTRIPE_WEBHOOK_URL,
        views.ProcessWebhookView.as_view(),
        name="webhook"
    ),
]

djstripe/templates/djstripe/base.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <!-- Modal for server update -->
  <div class="modal fade" id="in-progress">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Server Update In-Progress <img class="pull-right" src="{% static 'img/in-progress.gif' %}" /></h4>
        </div>
        <div class="modal-body">
            <div class="progress">
                <div class="progress-bar" style="width: 0%;"></div>
            </div>
        </div>

      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
{% endblock %}

djstripe/templates/djstripe/cancel_subscription.html
{% extends "djstripe/base.html" %}

{% block title %}Cancel Subscription{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
        <h2>Cancel Subscription</h2>
        {% if not customer.subscription %}
            <p>You have no subscription on file.</p>
        {% elif customer.subscription.status == customer.subscription.STATUS_CANCELED %}
            <p>Your subscription has already been canceled.</p>
        {% elif customer.subscription.is_status_temporarily_current %}
            <p>Your subscription has already been canceled.</p>
            <p>However, you can still use the site for another {{ customer.subscription.current_period_end|timeuntil }}.</p>
        {% else %}
            <p class="lead">
              Are you sure you want to cancel your subscription?
            </p>
            {% block cancellation_ramifications %}
            <h3>What you lose by cancelling your subscription:</h3>
            <ul>
              <li>Access to subscription-only content.</li>
              <li>Ability to use subscription-only features.</li>
            </ul>
            {% endblock cancellation_ramifications %}

            <h3>Are you sure you want to cancel?</h3>
            <form action="{% url 'djstripe:cancel_subscription' %}" method="post" id="cancel-form">
                {% csrf_token %}
                <button class="btn btn-danger">Cancel my subscription!</button>
            </form>
        {% endif %}
    </div>
</div>
{% endblock content %}

djstripe/templates/djstripe/subscribe.html
{% extends "djstripe/base.html" %}
{% load static %}

{% block title %}Choose a Subscription{% endblock title %}

{% block content %}
{{ block.super }}
<h2>Choose a Subscription</h2>

{% if error %}
    <div class="alert alert-error">{{ error }}</div>
{% endif %}
{% if view.error %}
    <div class="alert alert-error">{{ view.error }}</div>
{% endif %}

<div class="row">
    {% for plan in plans %}
      {% with plan_count=plans.count %}
        <div class="col-xs-12">
      {% endwith %}
            {% if customer.subscription.plan == plan and customer.subscription.is_valid %}
            <div class="btn btn-default disabled">
            {% else %}
            <a class="btn btn-primary" href="{% url 'djstripe:confirm' plan_id=plan.id %}" role="button">
            {% endif %}
                  {% with image=plan.image|default:"img/default-plan-image.png" %}
                    <img src="{% static image %}" class="img-thumbnail" />
                  {% endwith %}
                  <h3>{{ plan.name }}</h3>
                  <p>{{ plan.description }}</p>
            {% if customer.subscription.plan == plan and customer.subscription.is_valid %}
            </div>
            <h4>Your Current Plan</h4>
            {% else %}
            </a>
              {% if customer.subscription.plan.amount < plan.amount %}
                <h4>Upgrade</h4>
              {% elif customer.subscription.plan.amount > plan.amount %}
                <h4>Downgrade</h4>
              {% endif %}
            {% endif %}
        </div>
    {% endfor %}
</div>

{% endblock content %}